### ISSUE TITLE
Docs: fixed FAB

### ISSUE THREAD

**Issue by darthsitthiander** [sherweb/ngx-materialize#240]
I'd suggest adding the following to the documentation for floating buttons:

Wrap your button in the following div to make it fixed:
`<div class="fixed-action-btn">[Button code...]</div>`

Or am I doing something wrong? Couldn't find it anywhere.

**Comment by jfcere** [comment]
@darthsitthiander its a good idea!
You didn't miss anything, it wasn't anywhere in our documentation.
