### ISSUE TITLE
Tooltip on Checkboxes

### ISSUE THREAD

**Issue by darthsitthiander** [sherweb/ngx-materialize#291]
When adding a tooltip to a checkbox, I noticed some weird behavior. I wasn't really able to reproduce it in a Stackblitz but here is it anyways: https://stackblitz.com/edit/ngx-materialize-yeieku

I made a screenshot as well to demonstrate the behavior. The Tooltip hovers around the checkbox even if the checkbox has a label. It should surround checkbox AND label if both are present. Make for better readability, so hence why I figured this must either be a bug or not implemented.

Here pic: https://imgur.com/6rpTptP

**Comment by scote** [comment]
Did you try it on `mz-checkbox-container` instead of `input`?

**Comment by darthsitthiander** [comment]
Hi scote, Yes I did. You can see my code in the stackblitz I posted in app/app.component.html. Although the Stackblitz isn't able to produce the tooltip at all. Thanks for your time.

**Comment by scote** [comment]
I found this bug on Materialize. We have to put the tooltip on checbox label.

**Comment by scote** [comment]
The fix will be part of the next release.
