### ISSUE TITLE
mz-tab: Can't use text with characters with tilde as tab names

### ISSUE THREAD

**Issue by caom92** [sherweb/ngx-materialize#295]
## Expected Behavior
If I input a text that has special characters (specifically, characters with accents, tildes and diaeresis, like ó, ñ or ü) to the `[label]` property of the `mz-tab-item` component, the text should be displayed as the tab name and the user should still be able to click on it and the corresponding content should correctly be displayed.

## Current Behavior
When a text with special characters is input to the `[label]` property of the `mz-tab-item` component, the text is correctly displayed, but the moment the user click on the tab, the component's execution halts with a syntax error message and then it tries to navigates to another (invalid) page.

## Possible Solution
I think that the problem here is that the `[label]` property is responsible for 2 different functionalities within the component:

1. It configures the text to be displayed inside the tab
2. It directly determines how the content will be displayed when the tab is clicked (apparently through the use of HTML links or something of the sort)

Maybe if 2 different properties are provided --one for the tab name and one for determining the content navigation-- this issue can be fixed without requiring to re-think the tab content navigation. 

## Steps to Reproduce (for bugs)
Here's an example code that can reproduce the problem; first the texts for the tabs' names that are stored in `tabs.names` are  in english, so no special characters are being used --the tab component works fine. But when the "Change Language" button is pressed, the texts in `tabs` change to spanish, where 2 of them use a special character (ó and á specifically). When the user clicks on one of these tabs, I get the following error message: 

`Error: Syntax error, unrecognized expression: #m%C3%B3dulos`

and then the application tries to navigate to a different webpage (probably because it is trying to resolve an invalid HTML link, since HTML links do not allow special characters).

### HTML
```html
<button mz-button (click)="onLanguageChanged()">
  Change Language
</button>
<br>
<mz-tab>
  <mz-tab-item [label]='tabs.names.programs' [active]="'true'">
    {{ tabs.content.programs }}
  </mz-tab-item>
  <mz-tab-item [label]='tabs.names.modules'>
    {{ tabs.content.modules }}
  </mz-tab-item>
  <mz-tab-item [label]='tabs.names.logs'>
    {{ tabs.content.programs }}
  </mz-tab-item>
</mz-tab>
```

###  TypeScript
```typescript
import { Component, OnInit } from '@angular/core'

@Component({
  templateUrl: '../../templates/app/test.html'
})
export class TestComponent implements OnInit
{ 
  private tabs = {
    names: {
      programs: null,
      modules: null,
      logs: null
    },
    content: {
      programs: null,
      modules: null,
      logs: null
    }
  }

  private readonly translations = {
    en: {
      names: {
        programs: "Programs",
        modules: "Modules",
        logs: "Logs"
      },
      content: {
        programs: "Programs' Tab",
        modules: "Modules' Tab",
        logs: "Logs' Tab"
      }
    },
    es: {
      names: {
        programs: "Programas",
        modules: "Módulos",         // Note the special character ó here
        logs: "Bitácoras"           // and the special character á here
      },
      content: {
        programs: "Pestaña de programas",
        modules: "Pestaña de módulos",
        logs: "Pestaña de bitácoras"
      }
    }
  }

  private isEnglish: boolean = true

  ngOnInit(): void {
    this.tabs = this.translations['en']
  }

  private onLanguageChanged(): void {
    this.isEnglish = !this.isEnglish
    const lang = (this.isEnglish) ? 'en' : 'es'
    this.tabs = this.translations[lang]
  }
}
```

## Context
One project I'm working with requires support for both the spanish and english languages, so many of the texts displayed change dynamically depending on the language that the user has selected, including the names of the tabs. A quick workaround is to simply avoid inputing text with special characters to the `[label]` property. In spanish this pose no problem, since the missing accents do not affect the meaning of the words (in this case at least). However, I imagine, that this bug can be reproduced by inputing text in ANY language that uses special characters to the `[label]` property, not just spanish characters. So, for example, if somebody inputs text in chinese, the `mz-tab` component won't work at all. 

Also, I'm not 100% sure of what happens after the syntax error is displayed. In my case, since I'm using ui-router, I get navigated to a default page that I configured in my application, but when I inspected the HTML code I noticed that tabs get transformed to `<a>` tags where the `href` value corresponds to the value assign to `[label]`, so I assume that the application is trying to navigate to an invalid webpage.

## Your Environment
* Version used: 1.7.2
* Angular version used: 5.2.2
* Browser Name and version: Firefox 58.0.2
* Operating System and version (desktop or mobile): Ubuntu 16.04.4 LTS

**Comment by scote** [comment]
You can specify a different tab id for your tab item with the property `tabItemId`. When this attribute is not specify the component use the tab label as id and this did not work well with special characthers.

**Comment by scote** [comment]
This should be fixed.
