### ISSUE TITLE
Help with Toast

### ISSUE THREAD

**Issue by cassiodanilo** [sherweb/ngx-materialize#299]
Docs says on Toast secion: "... **If you call an external function instead of in-line JavaScript, you will not need to escape quotation marks.**"

```
export class MyComponent {
  
  constructor(
    private toastService: MzToastService,
  ) { }
  
  clickButton(): void {
    this.toastService.show(<span>I am a custom toast!</span><button class="btn-flat white-text medium" onclick="showLog()">CLICK ME</button>);
  }

  showLog(): void {
    console.log('Works');
  }
}
```

How do I call method _showLog()_ from toast onclick action?

**Comment by scote** [comment]
Can you make a Stackblitz example? Because I don't what you did wrong in your code.

**Comment by skrillexmau** [comment]
@cassiodanilo  I guess i got the answer. You need to write the function inside the onClick property.
