### ISSUE TITLE
I'm trying to implement a select and getting the following error: ERROR TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by ronjohn83** [sherweb/ngx-materialize#307]
MemberEditComponent.html:65 ERROR TypeError: Cannot read property 'apply' of undefined
    at RendererAdapter.invokeElementMethod (core.js:12032)
    at MzSelectDirective.initMaterialSelect (select.directive.js:79)
    at MzSelectDirective.handlePlaceholder (select.directive.js:178)
    at Object.placeholder (select.directive.js:60)
    at eval (handle-prop-changes.js:23)
    at Array.forEach (<anonymous>)
    at MzSelectDirective.HandlePropChanges.executePropHandlers (handle-prop-changes.js:20)
    at MzSelectDirective.handleProperties (select.directive.js:118)
    at MzSelectDirective.ngOnInit (select.directive.js:40)
    at checkAndUpdateDirectiveInline (core.js:12369)

 <div class="looking-for sub-section">
                <div class="row">
                  <h3>Looking For</h3>
                  <div class="col s12 m6 border">
                    <mz-input-container>
                      <input mz-input [label]="'City'" [validate]="true" id="txtCity" placeholder="Enter your city" length="150" type="email">
                    </mz-input-container>

                  </div>
                  <div class="col s12 m6 border">
                    <mz-select-container>
                      <select mz-select id="options-select" [label]="'Label'" [placeholder]="'Placeholder'">
                        <optgroup label="Group 1">
                          <option data-icon="assets/select-icon-1.jpg" class="left circle">Option 1</option>
                          <option data-icon="assets/select-icon-2.jpg" class="left circle">Option 2</option>
                        </optgroup>
                        <optgroup label="Group 2">
                          <option data-icon="assets/select-icon-3.jpg" class="left circle">Option 3</option>
                        </optgroup>
                      </select>
                    </mz-select-container>
                  </div>

**Comment by scote** [comment]
Like I said in your other issue can you reproduce this issue on Stackblitz and share it to us.
https://stackblitz.com/edit/ngx-materialize

**Comment by ronjohn83** [comment]
I did and posted it to github this morning with the link.

**Comment by jfcere** [comment]
The problem is pretty much the same thing as for the `mz-chip-input` issue you posted before, you need to load `jquery.min.js` before `materialize.min.js`.

You can see the fixed stackblitz example here: https://stackblitz.com/edit/ngx-materialize-8yd88m

That being said, the problem was already present in our base stackblitz ... we will fix it.

**Comment by ronjohn83** [comment]
I am doing that. Check the screen shot below.



On Wed, Apr 4, 2018 at 7:09 PM, Jean-Francois Cere <notifications@github.com

**Comment by jfcere** [comment]
What screenshot?

**Comment by jfcere** [comment]
Sorry still no screenshot ... but your are right, the only way is to put jQuery before Materialize

**.angular-cli.json**
```diff
"scripts": [
+ "../node_modules/jquery/dist/jquery.min.js",
+ "../node_modules/materialize-css/dist/js/materialize.min.js"
],
```

**Comment by ronjohn83** [comment]
I don't understand how there is no screen shot but here is my script
array...

"scripts": [
"../node_modules/alertifyjs/build/alertify.min.js",
"../node_modules/hammerjs/hammer.js",
"../node_modules/jquery/dist/jquery.min.js",
"../node_modules/materialize-css/dist/js/materialize.min.js"
],


On Wed, Apr 4, 2018 at 7:26 PM, Jean-Francois Cere <notifications@github.com

**Comment by jfcere** [comment]
It seems right, can I access your repository?

**Comment by ronjohn83** [comment]
Currently the project is only local. I'm going to do npm uninstall then
install and see if that helps. Maybe the setup is wrong even though i doubt
it because I have a few controls working such text input but i have a few
that doesn't like chips, select and dropdown.

On Wed, Apr 4, 2018 at 7:31 PM, Jean-Francois Cere <notifications@github.com

**Comment by ronjohn83** [comment]
Good morning Guys,

I'm still trying to resolve these issues because if not i'm going to have
to start over with bootstrap and that will be a nightmare given the fact
i'm 70% of the way through this project. Can you tell me if this means
anything to you?

Uncaught TypeError: this.chipInputElement.material_chip is not a function
    at MzChipInputComponent.get [as value] (chip-input.component.js:17)
    at eval (chip-input.component.js:42)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2025)

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@angular/core");
var forms_1 = require("@angular/forms");
var MzChipInputComponent = (function () {
    function MzChipInputComponent(elementRef, zone) {
        this.elementRef = elementRef;
        this.zone = zone;
        this.add = new core_1.EventEmitter();
        this.delete = new core_1.EventEmitter();
        this.select = new core_1.EventEmitter();
        //#endregion ControlValueAccessor
        this.onChangeCallback = function (data) { };
    }
    Object.defineProperty(MzChipInputComponent.prototype, "value", {
        get: function () {
            return this.chipInputElement.material_chip('data');
        },
        enumerable: true,
        configurable: true
    });
    MzChipInputComponent.prototype.ngOnInit = function () {
        this.initElements();
        this.initMaterializeChip();
    };
    MzChipInputComponent.prototype.ngOnDestroy = function () {
        this.chipInputElement.off('chip.add');
        this.chipInputElement.off('chip.delete');
        this.chipInputElement.off('chip.select');
    };
    MzChipInputComponent.prototype.initElements = function () {
        this.chipInputElement = $(this.elementRef.nativeElement);
    };

**Comment by ronjohn83** [comment]
Does it mean anything that i'm using the latest version of Angular (5)?
Errors such as this seems to be due to changes in versions of angular

MemberEditComponent.html:45 ERROR TypeError: Cannot read property 'apply'
of undefined
    at RendererAdapter.invokeElementMethod (core.js:12032)
    at MzSelectDirective.initMaterialSelect (select.directive.js:79)
    at MzSelectDirective.handlePlaceholder (select.directive.js:178)
    at Object.placeholder (select.directive.js:60)
    at eval (handle-prop-changes.js:23)
    at Array.forEach (<anonymous>)
    at MzSelectDirective.HandlePropChanges.executePropHandlers
(handle-prop-changes.js:20)
    at MzSelectDirective.handleProperties (select.directive.js:118)
    at MzSelectDirective.ngOnInit (select.directive.js:40)
    at checkAndUpdateDirectiveInline (core.js:12369)

For instance, see this link
<https://medium.com/bitmaker-software/my-most-puzzling-angular-2-errors-181c1331435b>
and read " *Uncaught TypeError: Cannot read property ‘apply’ of undefined"*

**Comment by scote** [comment]
Our library should be compatible with project using Angular 5 even if we are on Angular 4. Your project have something wrong in your configuration if it tell you the chip function does not exist.

**Comment by jfcere** [comment]
If you look carefully in the StackBlitz examples I posted yesterday, you'll see that it uses Angular 5.2.9 (which is the latest non beta/release candidate version) ... 

![image](https://user-images.githubusercontent.com/6987084/38367705-6f5ecac0-38b1-11e8-9835-a2de3b1ada61.png)

As stated by @scote ... please post your `.angular-cli.json` file.

**Comment by OzzyTheGiant** [comment]
Additionally, the Materialize library has been updated to 1.0.0 and no longer uses jQuery nor Hammer.js, so ngx-materialize needs to accommodate for those changes.

**Comment by jonathanestefani** [comment]
Dentro da sua classe implemente o método ngOnInit e coloque esse script. Quebrará um galho até eles ajustarem as bibliotecas, porém você terá que usar html puro do site materializecss.com.

`ngOnInit() {
    console.log("entrou aqui");
      var elems = document.querySelectorAll('select');
      console.log(elems);
      var instances = window.M.FormSelect.init(elems, {});
  }
`

Exemplo:

`import { Component, OnInit } from '@angular/core';
import { MzSelectModule } from 'ngx-materialize'

@Component({
  selector: 'app-home',
  templateUrl: './cadastro.html',
  styleUrls: ['./cadastro.css']
})
export class Cadastro implements OnInit `{`
  constructor() {
  }

  ngOnInit() {
    console.log("entrou aqui");
      var elems = document.querySelectorAll('select');
      console.log(elems);
      var instances = window.M.FormSelect.init(elems, {});
  }
}
`

**Comment by jonathanestefani** [comment]
Caso queiram fazer de forma que não de problema na transpilação, façam assim:
Lembrando que, você terá que usar html puro do site materializecss.com.

Exemplo:

`import { Component, OnInit } from '@angular/core';
import { MzSelectModule } from 'ngx-materialize'

@component({
selector: 'app-home',
templateUrl: './cadastro.html',
styleUrls: ['./cadastro.css']
})
export class Cadastro implements OnInit {
constructor() {
}

ngOnInit() {
     eval("var elems = document.querySelectorAll('select');");
     eval("window.M.FormSelect.init(elems, {});");
     // para datepicker
     eval("var elems = document.querySelectorAll('.datepicker');");
     eval("window.M.Datepicker.init(elems, {});");
}
}
