### ISSUE TITLE
errorMessageResource l18n

### ISSUE THREAD

**Issue by kostkams** [sherweb/ngx-materialize#313]
Hi,

I try to combine the static errorMessageResource with l18n. So when I change the app language, the error messages should change also. Is this possible? I use ng2-translate as module.

Something like that
` this.errorMessageResources = {
        companyName: {
          minlength: 'Register.Errors.CompanyName'
        },`

Thx

**Comment by scote** [comment]
I recommend you to use ngx-translate. I know it work with this one because we use it on internal application.
