### ISSUE TITLE
Feature request: Select with search

### ISSUE THREAD

**Issue by pierresilva** [sherweb/ngx-materialize#320]
First I want to thank for this plugin ... it's fantastic.

I want to know if there are plans to add select functionality with search engine?

It would be amazing to have that functionality.

![36095877-3f5d481e-0ff4-11e8-9034-9639bb3239c6](https://user-images.githubusercontent.com/2513617/39842887-1f9c72f4-53ae-11e8-8700-e3c31b86c2e7.png)

 #Reguards.

**Comment by scote** [comment]
You can use the `autocomplete` input (https://sherweb.github.io/ng2-materialize/input). It's not select component but the behavior is very similar.
