### ISSUE TITLE
Navbar not beign responsive

### ISSUE THREAD

**Issue by NicolasHz** [sherweb/ngx-materialize#326]
since the last update the: 
<mz-navbar>
  <a href="#" class="brand-logo">Logo</a>
  <mz-navbar-item-container [align]="'right'">
    <mz-navbar-item><a href="#">Sass</a></mz-navbar-item>
    <mz-navbar-item><a href="#">Components</a></mz-navbar-item>
    <mz-navbar-item><a routerLink="js">JavaScript</a></mz-navbar-item>
  </mz-navbar-item-container>
</mz-navbar>

archived responsive behavior, but now it hasnt.

**Comment by jfcere** [comment]
Are you sure about this? If you look at the [navbar demo page](https://sherweb.github.io/ng2-materialize/navbar) and play with the width of the browser it seems to correctly behave.

![navbar-responsiveness](https://user-images.githubusercontent.com/6987084/40060521-d41e1226-5824-11e8-96d4-de1d723fcecd.gif)

If this is the case can you reproduce in [StackBlitz](https://stackblitz.com/edit/ngx-materialize)?

**Comment by jfcere** [comment]
Alright I think I get what you mean ... the one with right alignment (like your example) seems to not behave as the materialize website.

#### ng2-materialize
![navbar-responsiveness-right-aligned](https://user-images.githubusercontent.com/6987084/40060897-a25da6f6-5825-11e8-81d8-68ff5607d83b.gif)

#### materializecss
![materialize-navbar-responsiveness-right-aligned](https://user-images.githubusercontent.com/6987084/40061082-1b5bbcaa-5826-11e8-9e37-42067172dfa3.gif)

**Comment by NicolasHz** [comment]
Yes, before the last update it was that behavior but not now.
Anyways, this is a great library! keep the great work! 
Regards!
