### ISSUE TITLE
Is this package going to work with materialize 1.0.0 rc1 ?

### ISSUE THREAD

**Issue by atindra** [sherweb/ngx-materialize#331]
Hi,

From the example I saw on the site, it seems that this works with materialize 0.9, but will it work with 1.0 rc1 ? Especially considering that there has been major rewrite.

Thanks
Atindra

**Comment by scote** [comment]
No, our version is base on 100.2. We will upgrade to version 1.0.0 when it's released.

**Comment by dimoreira** [comment]
@scote Any news on update guys? **v1.0.0** has been released 6 months ago. We have some plans to to this?

**Comment by scote** [comment]
Sadly I am not working on this project anymore. So I don't know if it will ever be upgraded to the latest version.

**Comment by dimoreira** [comment]
@scote Sad to hear that. @jfcere still working on this?
