### ISSUE TITLE
MzCheckboxModule not working.

### ISSUE THREAD

**Issue by andi2garcia** [sherweb/ngx-materialize#334]
Environment:
 Angular 6 (just upgraded).
Jquery 3.3.1.
Materialize 1.0.0-rc.2

It all works but MzCheckboxModule doesn't, just followed the example by adding this to component (obviously after adding modules and etc, it throws no error, just doesn't renders):
<mz-checkbox-container>
  <input mz-checkbox
    [label]="'Label'"
    id="checkbox-id"
    type="checkbox">
</mz-checkbox-container>

It just shows the label, and not the checkbox at all.

**Comment by andi2garcia** [comment]
It works smooth with 0.100.2.
May we wait for the Materialize 1.0.0 final version to upgrade it?

**Comment by scote** [comment]
You should not use Materialize 1.0.0. Our code is based on version 0.100.2.
