### ISSUE TITLE
MzMediaService is not compatible with Angular Universal

### ISSUE THREAD

**Issue by christophstach** [sherweb/ngx-materialize#337]
If you use server side rendering with angular universal, the MzMediaService produces an error,
while compiling the server app.

## Expected Behavior
It shouldn't throw an error on the server side of the application.

## Possible Solution
To fix this bug the constructor of the MzMediaService class should  be aware whether it was called on the client or on the server side. Just on the client side the this.registerWindowResizeListener() must be called.

## Steps to Reproduce (for bugs)
1. Set up an angular universal project
2. Import MzMediaModule to for example the app module
3. Run a server build

**Comment by jfcere** [comment]
PR has been merged and will be part of the next release.
